### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by cyinen** [HaoliangZhou/CEPrompt#3]
您好，使用你们提供的代码和脚本，我在 RAF-DB 上第一阶段的 ACC 只能达到 0.8990， 第二阶段的准确率只有 0.9003。可以提供一下你们做 align的代码吗，我怀疑是处理不一致导致的问题

**Comment by cyinen** [comment]
使用提供的预训练权重测试，在 AffectNet 上只有 64.79%的准确率。
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/dca96ab2-daee-404e-91df-d6d0250099e2">

**Comment by HaoliangZhou** [comment]
> 您好，使用你们提供的代码和脚本，我在 RAF-DB 上第一阶段的 ACC 只能达到 0.8990， 第二阶段的准确率只有 0.9003。可以提供一下你们做 align的代码吗，我怀疑是处理不一致导致的问题

您好，关于数据集，我们采用的是APViT中处理好的数据，具体可以参考这里：https://github.com/youqingxiaozhua/APViT

**Comment by HaoliangZhou** [comment]
> 使用提供的预训练权重测试，在 AffectNet 上只有 64.79%的准确率。
你好，关于这个结果可能是有3点原因：
（1）是环境配置或机器差异，
（2）是请问是否用的2阶段的权重，
（3）是AffectNet的实验我们代码输出的是ACC，然后需要进一步保存其预测值并额外计算Mean class acc，保存GT和预测值的代码具体可以参考这一行https://github.com/HaoliangZhou/CEPrompt/blob/master/engine_fer_second_stage.py#L117
